### ISSUE TITLE
result misalignment 

### ISSUE THREAD

**Issue by waiyc** [ktgiahieu/Fast-PPF#1]
Hi,

I tried to run the algorithm and found out that the result is different.
Any ideas on how to eliminate the misaligned part?
 
![Screenshot from 2021-08-24 15-56-16](https://user-images.githubusercontent.com/11879145/130579315-121f77a9-36eb-4d7b-aa51-596cb2b43a7f.png)

**Comment by chengm0-0** [comment]
I meet the same question. Have you solved it?

**Comment by chengm0-0** [comment]
I guess I solved the problem. This problem is due to the problem of the method of calculating PPF eigenvectors in PCL library. You can refer to these website:
https://github.com/PointCloudLibrary/pcl/issues/1131
https://github.com/PointCloudLibrary/pcl/issues/4701

**Comment by ktgiahieu** [comment]
Sorry guys, I remembered now. There is a bug in the implementation of PCL library, specifically in this file [https://github.com/PointCloudLibrary/pcl/blob/master/features/src/ppf.cpp](url), where the f1,f2,f3 needs to use arccos to calculate the angle. The correct implementation should be:

```
bool
pcl::computePPFPairFeature (const Eigen::Vector4f &p1, const Eigen::Vector4f &n1,
                            const Eigen::Vector4f &p2, const Eigen::Vector4f &n2,
                            float &f1, float &f2, float &f3, float &f4)
{
  Eigen::Vector4f delta = p2 - p1;
  delta[3] = 0.0f;
  // f4 = ||delta||
  f4 = delta.norm ();

  delta /= f4;

  // f1 = n1 dot delta
  f1 = acos(n1[0] * delta[0] + n1[1] * delta[1] + n1[2] * delta[2]);
  // f2 = n2 dot delta
  f2 = acos(n2[0] * delta[0] + n2[1] * delta[1] + n2[2] * delta[2]);
  // f3 = n1 dot n2
  f3 = acos(n1[0] * n2[0] + n1[1] * n2[1] + n1[2] * n2[2]);

  return (true);
}
```
In my day, I downloaded the PCL source code and rebuild the hold PCL library. BUT looking back, you can just add this new function in the code and replace pcl::computePPFPairFeature (line 357 of [this file](https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/MyPPFRegistration.hpp#L357) ) with this new function.
Sorry but I currently don't have much time to test this out myself, you can try it and create a PR or just confirm back to me if successful, thank you.

**Comment by waiyc** [comment]
thank you for your reply. Have you verified that [this modification](https://github.com/PointCloudLibrary/pcl/pull/4702/files) solves the misalignment issue?

**Comment by waiyc** [comment]
Thank you for the reply. 
I will test it and update you again on the result. Or maybe @chengm0-0 already tested this ?

**Comment by chengm0-0** [comment]
I modified the PCL library and recompiled it. The effect is really better. I have another question. Does this code not realize the optimization of pose voting stage mentioned in the paper? I look at the code and find the pose voting completed using the PCL library.

**Comment by ktgiahieu** [comment]
There is the voting stage [here](https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/MyPPFRegistration.hpp#L396-L439).

**Comment by ktgiahieu** [comment]
In the original paper, the author took Np best poses, but I found that taking 0.3*best_score as a threshold for selecting poses will perform better, as we will have a pose verification later to eliminate false positive.

**Comment by chengm0-0** [comment]
Thank you for your reply! I'll read the following code again!

**Comment by wwh01875** [comment]
> 我想我解決了這個問題。這個問題是由於PCL庫中計算PPF特徵向量的方法的問題。您可以參考這些網站： [PointCloudLibrary/pcl#1131 ](https://github.com/PointCloudLibrary/pcl/issues/1131) [PointCloudLibrary/pcl#4701](https://github.com/PointCloudLibrary/pcl/issues/4701)
I would like to ask how to solve it

**Comment by biowe11** [comment]
sorry，I am a c++,pcl beginner, is the computePPFPairFeature function added to MyPPFRegistra.cpp？

**Comment by WangYan1123** [comment]
PCL1.11.1 also has this question? I compile this program by PCL1.11.1, it detected three models when there was only one target in my scene.
