### ISSUE TITLE
Add the acos in computePPFPairFeature ,is it really right?

### ISSUE THREAD

**Issue by JINGJAVA** [ktgiahieu/Fast-PPF#10]
bool
pcl::computePPFPairFeature (const Eigen::Vector4f &p1, const Eigen::Vector4f &n1,
                            const Eigen::Vector4f &p2, const Eigen::Vector4f &n2,
                            float &f1, float &f2, float &f3, float &f4)

**Comment by ktgiahieu** [comment]
Yes, it is. Some already confirmed that the results are better as [here](https://github.com/ktgiahieu/Fast-PPF/issues/1#issuecomment-1080098753).

**Comment by JINGJAVA** [comment]
Thank you very much for your reply, I have a new problem, when I modified the PCL library and recompiled it,running the program with scene5.pcd, there are four results after matching.I think the best output result is one,can you give me some advice,thanks.
![scene5](https://user-images.githubusercontent.com/102002924/227717777-1f2e3b3d-e251-4de4-b470-bc8659f98ec2.png)

**Comment by ghost** [comment]
> Thank you very much for your reply, I have a new problem, when I modified the PCL library and recompiled it,running the program with scene5.pcd, there are four results after matching.I think the best output result is one,can you give me some advice,thanks. ![scene5](https://user-images.githubusercontent.com/102002924/227717777-1f2e3b3d-e251-4de4-b470-bc8659f98ec2.png)

Hello, guy ! Have u ever resolved this problem ? Cause I'm also facing it now.

**Comment by Yfanmeng** [comment]
> Thank you very much for your reply, I have a new problem, when I modified the PCL library and recompiled it,running the program with scene5.pcd, there are four results after matching.I think the best output result is one,can you give me some advice,thanks. ![scene5](https://user-images.githubusercontent.com/102002924/227717777-1f2e3b3d-e251-4de4-b470-bc8659f98ec2.png)

Hi friend, could you please share the ppf.cpp related files in the compiled PCL? I don't know how to compile the PCL file after modifying the source code. Looking forward to your reply.
