### ISSUE TITLE
Migration Application for this Project.

### ISSUE THREAD

**Issue by ghost** [ktgiahieu/Fast-PPF#12]
Thank you for your open-source contribution! During the process of learning and using your code, I achieved good test results with the provided data. However, when I applied my own model and data, the performance was not satisfactory. I attempted to increase the number of ICP iterations (2000 iterations) and the point cloud sampling ratio (0.02), but it did not improve the poor results. Do you have any suggestions?Additionally, I found that the sampling measurements in this project are not suitable for large-scale models (in the order of meters). Considering both large-scale models and small-scale scenes, does it seem impossible to modify this algorithm to make it applicable?

**Comment by ghost** [comment]
![8a166905e7b018293d8f83563a912fa](https://github.com/ktgiahieu/Fast-PPF/assets/52433358/786d142e-3b6b-40fd-a0bd-b7dacedd87e1)

**Comment by ghost** [comment]
> ![8a166905e7b018293d8f83563a912fa](https://user-images.githubusercontent.com/52433358/255900504-786d142e-3b6b-40fd-a0bd-b7dacedd87e1.png)

This is the bad result here.

**Comment by ktgiahieu** [comment]
Hi,

I cannot see your object clearly in the image provided, and I noticed that there are some points from the background persist after Background Removal.

Can you share with me the point cloud of your scene and your object? Or perhaps more images from different viewpoints?

Regarding the scale of the scene, there is a variable that calculates the diameter of the object (distance from 2 furthest points). I suggedt you modify any "hard-coded" distance into ratio of the diameter to make it work in any given scale.

**Comment by ghost** [comment]
Thank you for your prompt response! I am using point clouds captured with Intel Realsense, which is why you can see pronounced shadows in the images (caused by the hardware of the device). However, this should not affect the recognition process. In this image, the object I want to recognize is a mobile phone.

Regarding the scale issue, the problem I am currently facing is that I want to match features in a point cloud from a scene with a field of view of one square meter to a model with a maximum distance of 5 meters. The voxel size obtained by multiplying the sampling rate you set at 0.04 is not suitable for this purpose. For this particular field of view, sampling at 20cm voxel size does not capture the scene's features adequately.
And how can I share my  point cloud of my scene and object to u?

**Comment by ktgiahieu** [comment]
If you look at the method implemented in the paper, you would notice that the object needs to have recognizable features in their surface. A flat surface like a mobile phone wouldn't work well using this method because the orthogonal vector of the surface of the mobile phone is identical with that of the ground. This method needs different directions of the orthogonal vectors at different points on the object to work well.

**Comment by ghost** [comment]
Thanks for your reply! In fact, I noticed the requirements for recognizable features of the model. I thought the protrusion of the mobile phone's camera could be used as one of the recognizable features, but it seems it's not distinctive enough. Thank you for your response!

**Comment by ghost** [comment]
I did another test, but it also seem not good. The first pic is my model, and the second is the result.
![229f4be68679aed9667a38f21d71427](https://github.com/ktgiahieu/Fast-PPF/assets/52433358/f53f5d97-5f86-450b-b735-504d35ce9a5c)
![15a9f06bd4585a3f005bea8a8af0fb6](https://github.com/ktgiahieu/Fast-PPF/assets/52433358/e5da088e-8627-4a14-b741-6eb728762bcb)
