### ISSUE TITLE
招聘

### ISSUE THREAD

**Issue by yaoganxingwei** [ktgiahieu/Fast-PPF#14]
您好，我是松山湖材料实验室的团队负责招聘的工程师，我在猎聘看了下您的简历，感觉您比较符合我们的职位要求和技术能力，我们主要技术栈要求是C++,QT，图像算法和三维处理算法，方便聊聊吗？我的电话是17327892390。能否烦请帮忙加我微信（电话微信同号），我们详细聊一下。谢谢

**Comment by ktgiahieu** [comment]
Hi,

Thank you for the invitation. Unfortunately, I am not currently open for the job at the moment, but I wish you find the best candidates in the future.
