### ISSUE TITLE
Why are relatively complete objects not identified?

### ISSUE THREAD

**Issue by zhulz** [ktgiahieu/Fast-PPF#3]
Thanks to the author's excellent code, I got the correct result, but it is obvious that there are still four complete bearings in the figure that have not been identified. Why are relatively complete objects not identified?
![image](https://user-images.githubusercontent.com/12679016/163770458-8e83f66c-a517-4878-bb3f-2d78cdeeaf50.png)

**Comment by ktgiahieu** [comment]
My suggestion would be tuning down the threshold a little bit. There are 2 main threshold in this method:
- The ratio of votes (in stage B. Compute Pose Candidates) compared to the most voted pose (I use 0.3 here): 
https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/MyPPFRegistration.hpp#L435
- The ratio of votes (in stage C. Pose Verification) compared to the most voted pose (I use 0.5 here)::
https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/MyPPFRegistration.hpp#L554

If those 2 doesn't work out. You can try decreasing t_sampling here for better performance (but it will increase runtime):
https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.h#L18
