### ISSUE TITLE
Error : Instance no Aligned!

### ISSUE THREAD

**Issue by Aotemanliu** [ktgiahieu/Fast-PPF#5]
Dear Author:
Fortunately, I have read your project and compiled it successfully. The code provided by you can also be tested, and the effect is better. However, when I tested with other data sets, the error "**Leaf size is too small for the input dataset**" appeared. Then, I use third-party software to reduce the model and field cloud scale of the dataset, and the reduced dataset is basically the same as the dataset you provided (due to the use of third-party software, I am not sure what proportion of the reduction is in this process).
When I run the program again, the error "Leaf size is too small for the input dataset" no longer appears, but the problem "**Instance no Aligned**" appears again. I didn't get an answer when I consulted the data, so I want to ask you. Is it because the data set model used for me is inconsistent with the reduction ratio of the field cloud?
Looking forward to your reply,thank you!

**Comment by ktgiahieu** [comment]
If it is okay, you can provide some images of your point cloud and your 3D object so I can understand the situation better.

It is very hard for me to guess what is wrong with your data, since the method does not work on ALL type of objects and the parameters (such as leaf size) is very dependent on which type of camera you use, lighting circumstances, is the object mostly planar or edges, etc.
The method in this Fast-PPF repo is suitable for objects constructed by planar and cylinder shape, where as my other repo PPF-MEAM is more suitable for objects with a lot of edges. If your object does not falls into these 2 category, I would suggest choosing another method.

**Comment by Aotemanliu** [comment]
Dear author
    Thank you very much for your reply.
    Attachment 1 is the original data, and Attachment 2 is the adjusted data. Here's what I tested with this data set.
    Thanks again for your help and looking forward to your reply!
[附件2_adjusted data.zip](https://github.com/ktgiahieu/Fast-PPF/files/8822215/2_adjusted.data.zip)

[附件1_origin data.zip](https://github.com/ktgiahieu/Fast-PPF/files/8822200/1_origin.data.zip)
![Error message](https://user-images.githubusercontent.com/106364313/171592555-b4add821-3b53-4299-a24d-89209cdecf73.png)

**Comment by ktgiahieu** [comment]
With first glance, it seems that the background has not been discarded successfully, can you recheck the result of the background filter?

**Comment by ktgiahieu** [comment]
I have just had a look of your posted dataset and I must say the part has some small interior details. Because of it, when the camera captured the scene with it, the details are not going to be on the scene pointcloud and the normal vector are gonna be computed wrongly, hence the wrong detection. You should check the resolution of the captured scene and verify if my assumption is correct.

**Comment by Aotemanliu** [comment]
Dear author,
After receiving your reply, I checked the data set again and tested it again, but there was a new problem. What happened? Which parameter should I adjust?
![result](https://user-images.githubusercontent.com/106364313/172324998-7316cb55-b7b5-4636-ba67-933aad86fae7.png)

**Comment by ktgiahieu** [comment]
It is related to ICP problems. Try tuning these:
https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.h#L26-L27

**Comment by Aotemanliu** [comment]
When I tested using your data set, the model and scenario were attached to each other, as shown below.
![no 1](https://user-images.githubusercontent.com/106364313/172518080-73166db4-8f1c-4d16-9744-49fea47838f4.png)
But when I tested with my own data set, the model and the scene didn't stick together, they were far apart.as shown below.
![no 2](https://user-images.githubusercontent.com/106364313/172518174-ba718471-f0a8-41ad-bfb8-2420e79f3d7a.png)
What is the reason for this?
For your convenience, I will upload some files to you. Attachment 1 is the original data set, Attachment 2 is the adjusted data set (to be consistent with the size of your data set), and Attachment 3 is how I ran the program.
[附件1 original_data.zip](https://github.com/ktgiahieu/Fast-PPF/files/8857834/1.original_data.zip)
[附件2 adjusted data.zip](https://github.com/ktgiahieu/Fast-PPF/files/8857837/2.adjusted.data.zip)
[附件3 Program processing.zip](https://github.com/ktgiahieu/Fast-PPF/files/8857838/3.Program.processing.zip)

**Comment by ktgiahieu** [comment]
Just to clarify, by : "the model and the scene didn't stick together, they were far apart.as shown below.",
do you mean that the **predicted pose** is placed at a completely different location from the scene?

**Comment by ktgiahieu** [comment]
There is something wrong with the Normal Calculation step, let me check.

**Comment by Aotemanliu** [comment]
Yes, when I tested with the data you provided, when I ran to step 7, the predicted model was attached to the scenario. But when I tested it with my own data set, it didn't stick together.

**Comment by ktgiahieu** [comment]
Did you change any lines of code?

**Comment by Aotemanliu** [comment]
As I had the error "Not enough correspondences found. Relax your threshold parameters."
I modified the "icp_max_iter" and "icp_corr_distance" parameters in the ppf. h header file in Fast PPF. The diagram below. That's what you gave me. The above error will not occur after modification.
Other than that, I didn't change any lines of code.
![image](https://user-images.githubusercontent.com/106364313/172528631-2c085b80-7563-41ab-a653-e2825d5a4e96.png)

**Comment by ktgiahieu** [comment]
But after changing those lines, I guess that the **Normals** is still misplaced, am I correct?

**Comment by Aotemanliu** [comment]
But I don't have the idea to solve it now. Could you give me some hints?

**Comment by ktgiahieu** [comment]
I am guessing that there is some transformation done to the **scene** by mistake, and it effect the normal calculations. https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.cpp#L246-L247

**Comment by ktgiahieu** [comment]
I also noticed the cloud captured from your camera is orthogonal with Oy(green), while mine is Oz(blue). Maybe you should transformed the inputCloud so that it is similar to mine?
(P/s: somehow your normals in step 6 is also orthogonal to Oz, I guess that this approach should work)

**Comment by ktgiahieu** [comment]
Try adding 
`pcl::transformPointCloud(*latestCloud , *latestCloud , Eigen::Vector3f(0, 0, 0), Eigen::Quaternionf(0.7071, 0.7071, 0, 0));`
after 
https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.cpp#L159
(this `Eigen::Quaternionf(0.7071, 0.7071, 0, 0)` means rotates around Ox axis 90 degree, you can tune these values to suit your needs)

**Comment by wujilingfeng** [comment]
> Try adding `pcl::transformPointCloud(*latestCloud , *latestCloud , Eigen::Vector3f(0, 0, 0), Eigen::Quaternionf(0.7071, 0.7071, 0, 0));` after https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.cpp#L159 (this `Eigen::Quaternionf(0.7071, 0.7071, 0, 0)` means rotates around Ox axis 90 degree, you can tune these values to suit your needs)

Why is the normal calculation error？

**Comment by ktgiahieu** [comment]
I am just guessing at this point, we have to wait for him to clarify.

**Comment by Aotemanliu** [comment]
After adding code after line 159 in "ppf.cpp", the scene is perpendicular to OZ(blue). Unfortunately, the model and scenario did not match.
![step 3](https://user-images.githubusercontent.com/106364313/172551677-fd39042e-3fa1-4e5b-8d66-f58ec3dd1d0b.png)
After the normals are calculated, the position of the scene changes.
![step 6](https://user-images.githubusercontent.com/106364313/172551732-a109d685-182f-4a95-9f63-5f0b8bb180e4.png)
![step 7](https://user-images.githubusercontent.com/106364313/172551742-186d810a-ca0a-4a43-badc-4c573feb9e63.png)
![step 8](https://user-images.githubusercontent.com/106364313/172551764-729f3145-80bd-470c-a7df-68a3d4b04bbc.png)

**Comment by ktgiahieu** [comment]
Let's do a little debug. We will check if **scene** and **scene_keypoints** is transformed wrongly or not.
Try adding these lines after https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.cpp#L258

```
cout << "DEBUG: scene " << std::endl;
customViewer.viewer->removeAllShapes();
customViewer.viewer->removeAllPointClouds();
customViewer.viewer->addPointCloud(scene);
std::getchar();
cout << "DEBUG: scene_keypoints" << std::endl;
customViewer.viewer->removeAllShapes();
customViewer.viewer->removeAllPointClouds();
customViewer.viewer->addPointCloud(scene_keypoints);
std::getchar();
```
Then can you captured those 2 debug positions and post them here?

**Comment by Aotemanliu** [comment]
I've added the code the way you did, the 2 debug positions are shown below.
![scene](https://user-images.githubusercontent.com/106364313/172558589-5bc17827-2697-4676-a246-bf3ff1a109d4.png)
![scene_keypoints](https://user-images.githubusercontent.com/106364313/172558606-36b0ee9e-a211-4274-8d15-be0f2cbb04ea.png)

**Comment by ktgiahieu** [comment]
Is that with or without the `pcl::transformPointCloud(*latestCloud , *latestCloud , Eigen::Vector3f(0, 0, 0), Eigen::Quaternionf(0.7071, 0.7071, 0, 0));` ?

**Comment by Aotemanliu** [comment]
yes, i added this code to it.

**Comment by ktgiahieu** [comment]
Everything is fine haha, I really have no idea. Do you mind sharing your https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.cpp file?

**Comment by Aotemanliu** [comment]
this is  "PPF.cpp"file.
[PPF.txt](https://github.com/ktgiahieu/Fast-PPF/files/8859788/PPF.txt)

**Comment by ktgiahieu** [comment]
I tried printing out the values of the pointclouds and there is nothing wrong, only the visualizer displayed them wrongly. I guess that this is caused by converting .ply to .pcd file using some other software than PCL (the way you converted it). But the result is actually correct.
My advice is that you should try avoid converting .ply to .pcd

**Comment by Aotemanliu** [comment]
Dear author,
After receiving your reply yesterday, I checked the code and data set again.
1. In order to avoid the trouble caused by the conversion of ".ply "to".pcd "by the third party software, I wrote a piece of code to obtain the field cloud in".pcd "format and reduce its size to be similar to your data set (of course, the model will also be reduced in the same scale). Unfortunately, after the test, did not get good results.
2. Considering the error caused by normal vector calculation, I added normal vector visualization code in the project. When testing with my own data set, the normal orientation of the model was all inward, as shown in Fig 1. I thought it was this problem that caused the mismatch,  I added the following code with all its normal directions facing outward, as shown in Fig 2. However, this change does not change the result of the mismatch.
`for (int i = 0; i < normals->points.size(); ++i)
	{
		(*normals)[i].normal_x = (*normals)[i].normal_x * (-1);
		(*normals)[i].normal_y = (*normals)[i].normal_y * (-1);
		(*normals)[i].normal_z = (*normals)[i].normal_z * (-1);
	}`
![法线可视化](https://user-images.githubusercontent.com/106364313/172787474-bffd8512-850b-440c-96a8-d3a0b1fc8e72.png)
                                                                      Fig 1
![反转法线](https://user-images.githubusercontent.com/106364313/172787505-86e7548c-c762-4b11-86ef-85c231e4ad5e.png)
                                                                      Fig 2
Because I see that in your data set, the normal orientation that you get when you compute the normal vector is not always inward or outward. So I think it is not necessarily the problem of normal calculation, of course you can give me some advice on normal calculation.
3. Yesterday, you reminded me that there might be a problem with the location of scene cloud in the coordinate system, and added code.
`pcl::transformPointCloud(*latestCloud , *latestCloud , Eigen::Vector3f(0, 0, 0), Eigen::Quaternionf(0.7071, 0.7071, 0, 0));`
When I used your data set for testing today, I found that although the axis of green (OY) was perpendicular to the field cloud, as shown in Fig. 3, good matching results could also be obtained, as shown in Fig. 4.
![官方例子垂直场景](https://user-images.githubusercontent.com/106364313/172788316-07e133e5-3e9b-4655-bb34-ff629f0b5b4b.png)
Fig 3
![官方例子匹配结果](https://user-images.githubusercontent.com/106364313/172788336-33d2181f-3730-44c3-9be1-40bbb1396901.png)
Fig 4
Now I don't know what went wrong. Could you give me some hints? In addition, do you have other data sets? If convenient, could you please give me a copy so that I can test it again?
Looking forward to your reply!

**Comment by ktgiahieu** [comment]
All of the scenes I captured is already uploaded in this repo, and I am sorry to tell you that I cannot obtain more scene data because my setup is already gone after I finished this project, unfortunately. 
I also doesn't know the source of the issue, a hotfix could be adding `pcl::transformPointCloud(*latestCloud , *latestCloud , Eigen::Vector3f(0, 0, 0), Eigen::Quaternionf(0.7071, 0.7071, 0, 0));` only to the `scene` and `scene_keypoints` before displaying them, not when doing calculations.

**Comment by Aotemanliu** [comment]
Where exactly should I add this code?

**Comment by ktgiahieu** [comment]
[PPF.txt](https://github.com/ktgiahieu/Fast-PPF/files/8868768/PPF.txt)
I tried added it and it should be working for you (hotfix). However the matching part is not correct yet, feel free to tune the parameters.

**Comment by ktgiahieu** [comment]
![Screenshot from 2022-06-09 16-13-02](https://user-images.githubusercontent.com/42331617/172811583-3d117f3a-08ef-4540-ac99-fb97125a4281.png)
It still needs some tuning for better result. Also feel free to remove some uncessary std::cout for debug purpose.
Maybe your "normals inwards, outwards" idea is crucial here.

**Comment by Aotemanliu** [comment]
Dear author
After testing with the "ppf.cpp" file you gave me, my data set also matched the result you uploaded, but the match was incomplete (inaccurate), as shown in Fig 1.
![修改PPF cpp内容后结果3](https://user-images.githubusercontent.com/106364313/172971290-cf2af82e-521b-4d52-b6d1-ad96d56b8322.png)
Fig 1
In addition, I also used other PPF projects to test my data sets, and this project did not include ICP algorithms. The PPF algorithm in the project can achieve better matching. As shown in Fig 2.
![1](https://user-images.githubusercontent.com/106364313/172971318-52ed312d-5fe6-4103-855a-fe2a9b98fed7.png)
Fig 2
In your project, there is no initial matching between the model and the scene cloud before the implementation of ICP algorithm, as shown in Fig 3. Only after the implementation of ICP algorithm, that is after Step 9, can the model and the scene cloud match.
![123](https://user-images.githubusercontent.com/106364313/172971521-8ebf62b7-8933-4ac1-b205-544b91a9366f.png)
Fig 3
Can I understand that there is a problem in normal calculation, which leads to the failure of PPF algorithm to match?

Or before the implementation of ICP algorithm, PPF algorithm did not play its due role?

**Comment by ktgiahieu** [comment]
I think you should try detecting 1, then 2, then more parts in the scene. By testing with less objects, we can understand better those questions you asked earlier. It is hard for me to guess the problem as well.
