### ISSUE TITLE
This project keeps crashing and instances are not aligned when running

### ISSUE THREAD

**Issue by wwh01875** [ktgiahieu/Fast-PPF#6]
When I run the second step of this project, the FPS in the lower left corner of the VTK visualization is usually around 2000, which will cause the project to crash, but it seems to be only around 50~60 in your video. On the issue of alignment, I have followed your steps to modify the material in the PCL library and recompile PCL, and then run the project and still cannot align.

**Comment by wwh01875** [comment]
![S__159367177](https://user-images.githubusercontent.com/99259909/171997886-63c7348e-9b8a-4d3b-9f41-d0599f08944e.jpg)

**Comment by wwh01875** [comment]
![S__159367178](https://user-images.githubusercontent.com/99259909/171997913-85bc8516-65ab-428b-b7de-bed1769e7a26.jpg)
![S__159367179](https://user-images.githubusercontent.com/99259909/171997919-ad515538-d292-4118-9a42-f39f15be3bff.jpg)
![S__159367177](https://user-images.githubusercontent.com/99259909/171997923-41de58ea-27c5-410b-99bd-4331b35568d8.jpg)

**Comment by ktgiahieu** [comment]
This is also my first time seeing this kind of problem. Unfortunately, it is hard for me to recognize what is wrong as well.

**Comment by wwh01875** [comment]
I would like to ask how your thread part realizes the exception of allocation. How many CPUs does your computer have? I have consulted a lot of information and said that it is because of CPU preemption, but I have not found a solution yet. In addition, I would like to ask you about the inability to allocate In the standard question, do you mean that you need to go to PPF.cpp in PCL/features/src to change the BUG part you mentioned, then recompile and run your program to register?

**Comment by ktgiahieu** [comment]
- I only use a 4 core CPU for this project. 
- You should change lines https://github.com/PointCloudLibrary/pcl/blob/master/features/src/ppf.cpp#L43-L63 to:
```
bool
pcl::computePPFPairFeature (const Eigen::Vector4f &p1, const Eigen::Vector4f &n1,
                            const Eigen::Vector4f &p2, const Eigen::Vector4f &n2,
                            float &f1, float &f2, float &f3, float &f4)
{
  Eigen::Vector4f delta = p2 - p1;
  delta[3] = 0.0f;
  // f4 = ||delta||
  f4 = delta.norm ();

  delta /= f4;

  // f1 = n1 dot delta
  f1 = acos(n1[0] * delta[0] + n1[1] * delta[1] + n1[2] * delta[2]);
  // f2 = n2 dot delta
  f2 = acos(n2[0] * delta[0] + n2[1] * delta[1] + n2[2] * delta[2]);
  // f3 = n1 dot n2
  f3 = acos(n1[0] * n2[0] + n1[1] * n2[1] + n1[2] * n2[2]);

  return (true);
}
```
and recompiled PCL. It worked for me and some others.

**Comment by wwh01875** [comment]
Sorry to ask again, is your project executed on windows?
I executed it on ubuntu18.04 and executed it on a 12-core CPU. Is it because the thread is in ubuntu?

**Comment by ktgiahieu** [comment]
I executed it in both Windows and Ubuntu 18.04. And it works fine.

**Comment by LI0809** [comment]
> ![S__159367178](https://user-images.githubusercontent.com/99259909/171997913-85bc8516-65ab-428b-b7de-bed1769e7a26.jpg) ![S__159367179](https://user-images.githubusercontent.com/99259909/171997919-ad515538-d292-4118-9a42-f39f15be3bff.jpg) ![S__159367177](https://user-images.githubusercontent.com/99259909/171997923-41de58ea-27c5-410b-99bd-4331b35568d8.jpg)
I had the same problem.You can try lowering the version of the VTK visualization library to VTK6.It is possible that this condition will decrease or disappear.

**Comment by wwh01875** [comment]
> > ![S__159367178](https://user-images.githubusercontent.com/99259909/171997913-85bc8516-65ab-428b-b7de-bed1769e7a26.jpg) ![S__159367179](https://user-images.githubusercontent.com/99259909/171997919-ad515538-d292-4118-9a42-f39f15be3bff.jpg) ![S__159367177](https://user-images.githubusercontent.com/99259909/171997923-41de58ea-27c5-410b-99bd-4331b35568d8.jpg)
> > 我也遇到了同樣的問題。你可以嘗試將VTK可視化庫的版本降低到VTK6。這種情況有可能會或消失。

I installed VTK version 6.3 or do I need to downgrade it?

**Comment by LI0809** [comment]
> 

I switched to PCL1.10 and VTK6.3 a few days ago, so I also use VTK6.3, and the situation seems to be getting better. But I'm not sure if the XIO error will continue to appear. I'll test a few more times later and I'll give you an answer.

**Comment by LI0809** [comment]
> > > ![S__159367178](https://user-images.githubusercontent.com/99259909/171997913-85bc8516-65ab-428b-b7de-bed1769e7a26.jpg) ![S__159367179](https://user-images.githubusercontent.com/99259909/171997919-ad515538-d292-4118-9a42-f39f15be3bff.jpg) ![S__159367177](https://user-images.githubusercontent.com/99259909/171997923-41de58ea-27c5-410b-99bd-4331b35568d8.jpg)
> > > 我也遇到了同樣的問題。你可以嘗試將VTK可視化庫的版本降低到VTK6。這種情況有可能會或消失。
> 
> I installed VTK version 6.3 or do I need to downgrade it?

Sorry，very strange! Today I tested and ran the code many times. The first few times the code ran very smoothly, until I encountered an XIO error again in the middle, and then I encountered this error almost every time after that. So I don't know how to solve this problem, it has been bothering me for a long time，I guess it is the problem of VTK version, but I can't be sure. If you find a solution, please let me know, it would be greatly appreciated.
