### ISSUE TITLE
How to adjust the parameters of the background filter

### ISSUE THREAD

**Issue by wwh01875** [ktgiahieu/Fast-PPF#7]
I am using your project now, but the background filtering part cannot be completely removed after inputting my data and scene point cloud. How should I adjust it, dear author?
![S__163332098](https://user-images.githubusercontent.com/99259909/174811739-0125cbc2-4cd6-4c58-8e14-f2b5783c67b3.jpg)

**Comment by ktgiahieu** [comment]
You can try tuning 0.005 in this line:
https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.cpp#L198

**Comment by wwh01875** [comment]
What does the value of 0.005 mean? After I adjust it, it is still not ideal, and it is not completely divided

**Comment by ktgiahieu** [comment]
The 0.005 is the "width" of the planar which is estimated to removed. More information can be found here: https://pcl.readthedocs.io/projects/tutorials/en/latest/planar_segmentation.html
Usually if you already know the working zone, you can also extract the objects using a range of X, Y, Z for a better extraction.
